# Generated by Django 3.1.1 on 2020-10-03 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_remain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
